### ISSUE TITLE
 No such file or directory: u'./apps/kenya-compliance/setup.py'

### ISSUE THREAD

**Issue by kechkibet** [navariltd/kenya-compliance#1]
On installing the plugin,  get this error:

IOError: [Errno 2] No such file or directory: u'./apps/kenya-compliance/setup.py'

**Comment by muchai** [comment]
App dev is in progress. When it's ready, we will update you.

**Comment by GichanaMayaka** [comment]
> On installing the plugin, get this error:
> 
> IOError: [Errno 2] No such file or directory: u'./apps/kenya-compliance/setup.py'

Please respond with the environment versions for where you are attempting to install
